### ISSUE TITLE
Basic Link Creation

### ISSUE THREAD

**Issue by MisterJimson** [chandertech/turtlelinks#3]
- *.turtlelinks.com subdomains only
- Similar link structure to Firebase
- Saves links and database and navigates to link target when visited
- UI in Dashboard to create

**Comment by matekdev** [comment]
This PR will take care of this... I plan to add...

1. Creation of URL prefix 
2. Creation of dynamic links

The UI elements have been stubbed, now working on the database and API calls.

https://github.com/chandertech/turtlelinks/pull/5
